### ISSUE TITLE
branch is not compatible with php 8.1.0

### ISSUE THREAD

**Issue by gearosv2** [chriswest101/paynow#1]
Hi Chris,

Found your php library and would like to use it, however, the composer install is not working as my environment is on php 8.1.0, do you think you can fix that?

extract...
Installation failed, reverting ./composer.json and ./composer.lock to their original content.
[prince-george]$ composer require chriswest101/paynow
Cannot use chriswest101/paynow's latest version v1.0.1 as it requires php ^7.1 which is not satisfied by your platform.

In PackageDiscoveryTrait.php line 313:
                                                                                                                
  Package chriswest101/paynow has requirements incompatible with your PHP version, PHP extensions and Composer  
   version:                                                                                                     
    - chriswest101/paynow v1.0.1 requires php ^7.1 which does not match your installed version 8.1.0.

**Comment by leekaimun** [comment]
For the moment, edit composer.json to use this package but from an updated repo. Example:
```
   "require": {
        "php": "^8.0.2",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^9.19",
        "laravel/sanctum": "^3.0",
        "laravel/tinker": "^2.7",
        "chriswest101/paynow": "dev-phpversion"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/leekaimun/paynow"
        }
    ],
```
After that, run `composer update`.

**Comment by gearosv2** [comment]
Thanks!
