### ISSUE TITLE
QR codes not scannable.

### ISSUE THREAD

**Issue by hariidavinci** [chriswest101/paynow#4]
Hi there, 

During some internal test, i noticed that the paynow string generated by the CRC16 helper class were failing to return four character long  string. This results in a broken QR code. 

In order to replicate it, consider running the following script within a loop of 30 to 100. 

```
for( 0 to 30)
Paynow::generateDynamic(
    100.00,
    false,
    "O123456",
    (new DateTime())->modify("+ 1 hour"),
    "Clothing Company Pte Ltd",
    "SG",
    "Singapore",
    "2020111104G",
    null,
    false
);
endfor
```

You will notice that a few QR code will fail. 
Please review my PR to resolve this issue. I've added some explanation within the PR I've issued.
PR: https://github.com/chriswest101/paynow/pull/3/commits

Thanks.

**Comment by chriswest101** [comment]
@hariidavinci thanks for the input. Your PR has been merged.
